#
# Module manifest for module 'Az'
#
# Generated by: Microsoft Corporation
#
# Generated on: 11/2/2025
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '14.6.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd48d710e-85cb-46a1-990f-22dae76f6b5f'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with PowerShell and Windows PowerShell.
For more information about the Az module, please visit the following: https://learn.microsoft.com/powershell/azure/'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Az.Accounts'; ModuleVersion = '5.3.1'; }, 
               @{ModuleName = 'Az.Advisor'; RequiredVersion = '2.1.1'; }, 
               @{ModuleName = 'Az.Aks'; RequiredVersion = '7.0.0'; }, 
               @{ModuleName = 'Az.AnalysisServices'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.ApiManagement'; RequiredVersion = '4.1.0'; }, 
               @{ModuleName = 'Az.App'; RequiredVersion = '2.0.1'; }, 
               @{ModuleName = 'Az.AppConfiguration'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.ApplicationInsights'; RequiredVersion = '2.3.1'; }, 
               @{ModuleName = 'Az.ArcResourceBridge'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.ArizeAI'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.Attestation'; RequiredVersion = '2.1.1'; }, 
               @{ModuleName = 'Az.Automanage'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.Automation'; RequiredVersion = '1.11.2'; }, 
               @{ModuleName = 'Az.Batch'; RequiredVersion = '3.7.1'; }, 
               @{ModuleName = 'Az.Billing'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.Cdn'; RequiredVersion = '5.0.1'; }, 
               @{ModuleName = 'Az.CloudService'; RequiredVersion = '2.1.1'; }, 
               @{ModuleName = 'Az.CognitiveServices'; RequiredVersion = '1.16.0'; }, 
               @{ModuleName = 'Az.Compute'; RequiredVersion = '10.5.0'; }, 
               @{ModuleName = 'Az.ConfidentialLedger'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.ConnectedMachine'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.ContainerInstance'; RequiredVersion = '4.1.2'; }, 
               @{ModuleName = 'Az.ContainerRegistry'; RequiredVersion = '4.3.2'; }, 
               @{ModuleName = 'Az.CosmosDB'; RequiredVersion = '1.18.3'; }, 
               @{ModuleName = 'Az.DataBoxEdge'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.Databricks'; RequiredVersion = '1.10.1'; }, 
               @{ModuleName = 'Az.DataFactory'; RequiredVersion = '1.19.6'; }, 
               @{ModuleName = 'Az.DataLakeAnalytics'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.DataLakeStore'; RequiredVersion = '1.5.1'; }, 
               @{ModuleName = 'Az.DataMigration'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.DataProtection'; RequiredVersion = '2.8.0'; }, 
               @{ModuleName = 'Az.DataShare'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.DataTransfer'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.DesktopVirtualization'; RequiredVersion = '5.4.1'; }, 
               @{ModuleName = 'Az.DevCenter'; RequiredVersion = '2.0.2'; }, 
               @{ModuleName = 'Az.DeviceRegistry'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.DevTestLabs'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Dns'; RequiredVersion = '1.3.2'; }, 
               @{ModuleName = 'Az.DnsResolver'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.ElasticSan'; RequiredVersion = '1.5.0'; }, 
               @{ModuleName = 'Az.EventGrid'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.EventHub'; RequiredVersion = '5.4.0'; }, 
               @{ModuleName = 'Az.Fabric'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.FirmwareAnalysis'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.FrontDoor'; RequiredVersion = '1.13.0'; }, 
               @{ModuleName = 'Az.Functions'; RequiredVersion = '4.2.1'; }, 
               @{ModuleName = 'Az.HDInsight'; RequiredVersion = '6.4.0'; }, 
               @{ModuleName = 'Az.HealthcareApis'; RequiredVersion = '2.1.1'; }, 
               @{ModuleName = 'Az.HealthDataAIServices'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.IotHub'; RequiredVersion = '2.8.1'; }, 
               @{ModuleName = 'Az.KeyVault'; RequiredVersion = '6.4.1'; }, 
               @{ModuleName = 'Az.Kusto'; RequiredVersion = '2.4.0'; }, 
               @{ModuleName = 'Az.LambdaTest'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.LoadTesting'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.LogicApp'; RequiredVersion = '1.6.0'; }, 
               @{ModuleName = 'Az.MachineLearning'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.MachineLearningServices'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.Maintenance'; RequiredVersion = '1.5.1'; }, 
               @{ModuleName = 'Az.ManagedServiceIdentity'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.ManagedServices'; RequiredVersion = '3.1.2'; }, 
               @{ModuleName = 'Az.MarketplaceOrdering'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.Migrate'; RequiredVersion = '2.10.1'; }, 
               @{ModuleName = 'Az.Monitor'; RequiredVersion = '6.0.3'; }, 
               @{ModuleName = 'Az.MySql'; RequiredVersion = '1.5.0'; }, 
               @{ModuleName = 'Az.Network'; RequiredVersion = '7.23.0'; }, 
               @{ModuleName = 'Az.NetworkCloud'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.Nginx'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.NotificationHubs'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.OperationalInsights'; RequiredVersion = '3.3.0'; }, 
               @{ModuleName = 'Az.Oracle'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.PolicyInsights'; RequiredVersion = '1.7.2'; }, 
               @{ModuleName = 'Az.PostgreSql'; RequiredVersion = '1.4.0'; }, 
               @{ModuleName = 'Az.PowerBIEmbedded'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.PrivateDns'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.RecoveryServices'; RequiredVersion = '7.9.1'; }, 
               @{ModuleName = 'Az.RedisCache'; RequiredVersion = '1.11.0'; }, 
               @{ModuleName = 'Az.RedisEnterpriseCache'; RequiredVersion = '1.6.0'; }, 
               @{ModuleName = 'Az.Relay'; RequiredVersion = '2.1.2'; }, 
               @{ModuleName = 'Az.ResourceGraph'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.ResourceMover'; RequiredVersion = '1.3.1'; }, 
               @{ModuleName = 'Az.Resources'; RequiredVersion = '8.1.1'; }, 
               @{ModuleName = 'Az.Security'; RequiredVersion = '1.8.0'; }, 
               @{ModuleName = 'Az.SecurityInsights'; RequiredVersion = '3.2.1'; }, 
               @{ModuleName = 'Az.ServiceBus'; RequiredVersion = '4.1.1'; }, 
               @{ModuleName = 'Az.ServiceFabric'; RequiredVersion = '3.9.0'; }, 
               @{ModuleName = 'Az.SignalR'; RequiredVersion = '2.3.0'; }, 
               @{ModuleName = 'Az.Sql'; RequiredVersion = '6.3.0'; }, 
               @{ModuleName = 'Az.SqlVirtualMachine'; RequiredVersion = '2.4.0'; }, 
               @{ModuleName = 'Az.StackHCI'; RequiredVersion = '2.6.4'; }, 
               @{ModuleName = 'Az.StackHCIVM'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Storage'; RequiredVersion = '9.3.0'; }, 
               @{ModuleName = 'Az.StorageAction'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.StorageDiscovery'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.StorageMover'; RequiredVersion = '1.6.0'; }, 
               @{ModuleName = 'Az.StorageSync'; RequiredVersion = '2.5.2'; }, 
               @{ModuleName = 'Az.StreamAnalytics'; RequiredVersion = '2.1.1'; }, 
               @{ModuleName = 'Az.Support'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Synapse'; RequiredVersion = '3.2.3'; }, 
               @{ModuleName = 'Az.TrafficManager'; RequiredVersion = '1.3.0'; }, 
               @{ModuleName = 'Az.Websites'; RequiredVersion = '3.4.2'; }, 
               @{ModuleName = 'Az.Workloads'; RequiredVersion = '1.1.0'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ARM','ResourceManager','Linux','AzureAutomationNotSupported'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '14.6.0 - November 2025
Az.Accounts
* Updated Azure.Core from 1.45.0 to 1.47.3

Az.ArcResourceBridge
* Introduced various new features by upgrading code generator. Please see detail [here](https://github.com/Azure/azure-powershell/blob/main/documentation/Autorest-powershell-v4-new-features.md).

Az.Automanage
* Introduced various new features by upgrading code generator. Please see detail [here](https://github.com/Azure/azure-powershell/blob/main/documentation/Autorest-powershell-v4-new-features.md).

Az.Compute
* Updated Azure.Core from 1.45.0 to 1.47.3
* Added ''-Redeploy'' switch parameter for ''Update-AzHost'' cmdlet to enable dedicated host redeployment.
* Added ''-SupportedSecurityOption'' parameter to ''New-AzDiskConfig'' cmdlet.
* ComputeRP related cmdlets will now use 2025-04-01 version of the ComputeRP API.
* Added ''-AddProxyAgentExtension'' parameter (Switch) to ''New-AzVmss'' and ''New-AzVM''
* Added ''-AddProxyAgentExtension'' parameter (Bool) to ''Set-AzVMProxyAgentSetting'' and  ''Set-AzVmssProxyAgentSetting''

Az.ContainerRegistry
* Updated Azure.Core from 1.45.0 to 1.47.3

Az.CosmosDB
* Updated Azure.Core from 1.45.0 to 1.47.3

Az.DataFactory
* Added support for clusterResourceGroupAuthType property in HDInsightOnDemand linked services properties.

Az.DataLakeStore
* Updated Azure.Core from 1.45.0 to 1.47.3

Az.DataProtection
* Added support for AzureDataLakeStorage workload

Az.DeviceRegistry
* General availability for module Az.DeviceRegistry
* GA stable release of API version 2025-10-01 for Az.DeviceRegistry. New updates include:
    - Schema and Schema Version asynchronous delete. No longer synchronous.
    - Namespace Asset and Namespace Discovered Asset EventGroups.
    - Namespace Device x509 certificate authentication now supports intermediate certificates and key secret names.

Az.ElasticSan
* Supported auto scale when creating and updating an Elastic SAN.
    - ''New-AzElasticSan''
    - ''Update-AzElasticSan''
* Supported checking whether disk snapshot backup can be taken for volumes.
    - ''Test-AzElasticSanVolumeBackup''
    - ''Test-AzElasticSanVolumeRestore''

Az.IotHub
* Removed unused libraries

Az.KeyVault
* Updated Azure.Core from 1.45.0 to 1.47.3

Az.Migrate
* Fixed bugs in ''Initialize-AzMigrateLocalReplicationInfrastructure''
  - Correct AMH solution tool name of ''ServerMigration_DataReplication'' is now being passed in to address replication count missing and UX experience load issues in Azure Migrate on Azure portal.
* Address Join-Path compatibility issue in older version of PowerShell environment such as PowerShell 5.1 in the following commands
 - ''Initialize-AzMigrateLocalReplicationInfrastructure''
 - ''Initialize-AzMigrateReplicationInfrastructure''
 - ''New-AzMigrateLocalServerReplication''
 - ''Get-AzMigrateLocalServerReplication''
 - ''Set-AzMigrateLocalServerReplication''
 - ''Start-AzMigrateLocalServerMigration''

Az.Network
* Bug fix for ''AzureFirewallPolicy'' to ensure ''BasePolicy'' is properly set via ''Set-AzFirewallPolicy'' cmdlet either via pipe or direct value.

Az.PolicyInsights
* Updated Azure.Core from 1.45.0 to 1.47.3

Az.RecoveryServices
* Added Cross region restore support for new region - northeastus5.

Az.RedisEnterpriseCache
* Added a new required property: PublicNetworkAccess for Cluster.
* Updated the default value of AccessKeysAuthentication property for Database to ''Disabled''.

Az.ServiceFabric
* Removed ''ReimageByName'', ''ReimageById'', and ''ReimageByObj'' parameter sets from ''Set-AzServiceFabricManagedNodeType''.

Az.SignalR
* Updated Azure.Core from 1.45.0 to 1.47.3
* Added cmdlets for managing replicas:
    - Get-AzSignalRReplica: get replica(s) for SignalR
    - New-AzSignalRReplica: create a new replica for SignalR
    - Remove-AzSignalRReplica: remove a replica from SignalR
    - Restart-AzSignalRReplica: restart a SignalR replica
    - Start-AzSignalRReplica: start a SignalR replica
    - Stop-AzSignalRReplica: stop a SignalR replica
    - Update-AzSignalRReplica: update a SignalR replica
* Added cmdlets for managing network IP rules
    - New-AzSignalRNetworkIpRuleObject: create a new network IP rule object for SignalR
    - Add-AzSignalRNetworkIpRule: add network IP rule(s) to SignalR
    - Remove-AzSignalRNetworkIpRule: remove network IP rule(s) from SignalR

Az.Sql
* Updated with support for Immutable Long-Term Retention Backups
    - Updated ''Set-AzSqlDatabaseBackupLongTermRetentionPolicy'' cmdlet to expose ''TimeBasedImmutability'' and ''TimeBasedImmutabilityMode'' parameters.
    - Updated ''AzureSqlDatabaseBackupLongTermRetentionPolicyModel'' to add ''TimeBasedImmutability'' and ''TimeBasedImmutabilityMode'' properties.
    - Updated ''AzureSqlDatabaseLongTermRetentionBackupModel'' to add ''TimeBasedImmutability'', ''TimeBasedImmutabilityMode'', and ''LegalHoldImmutability'' properties.
    - Added new cmdlets ''Lock-AzSqlDatabaseLongTermRetentionBackupImmutability'' and ''Remove-AzSqlDatabaseLongTermRetentionBackupImmutability'' for managing time-based immutability on LTR backups.
    - Added new cmdlets ''Set-AzSqlDatabaseLongTermRetentionBackupLegalHold'' and ''Remove-AzSqlDatabaseLongTermRetentionBackupLegalHold'' for managing legal hold immutability on LTR backups.

Az.StackHCI
* Fixed bug: Buse boolean in comparision

Az.Storage
* Updated Azure.Core from 1.45.0 to 1.47.3
* Supported Blob Geo Replication SLA on Storage accounts
    - ''New-AzStorageAccount''
    - ''Set-AzStorageAccount''
* Supported enable Priority Replication when set object replication policy
    - ''Set-AzStorageObjectReplicationPolicy''
* Supported get and reconcile NSP Configuration on a Storage account: 
    - ''Get-AzStorageNetworkSecurityPerimeterConfiguration''
    - ''Invoke-AzStorageReconcileNetworkSecurityPerimeterConfiguration''

Az.Synapse
* Updated Azure.Core from 1.45.0 to 1.47.3
* Updated Azure.Analytics.Synapse.Artifacts to 1.0.0-preview.22

Az.Workloads
* Introduced various new features by upgrading code generator. Please see details [here](https://github.com/Azure/azure-powershell/blob/main/documentation/Autorest-powershell-v4-new-features.md).
* The parameters of the ''New-AzWorkloadsMonitor'', ''New-AzWorkloadsProviderInstance'' and ''Update-AzWorkloadsMonitor'' cmdlet will be changed by new Managed Identity settings.
    - Removed ''-IdentityType'' and ''-IdentityUserAssignedIdentity'' parameters.
    - Added ''-UserAssignedIdentity'' parameter. The type of ''UserAssignedIdentity'' is simplified to a list of strings that is used to specify the user''s assigned identity.
    - Added ''EnableSystemAssignedIdentity'' to enable/disable system-assigned identities.
'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

